# Generated by Django 5.1.6 on 2025-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
